#!/bin/bash

execdir=.

classpath=$(find $execdir -name '*.jar' | awk '{ printf("%s:", $1); } END { printf("%s", $1); }')
executable='rocks.voss.musicsync.application/rocks.voss.musicsync.application.Application'

java -classpath $classpath -p $execdir:$execdir/modules -m $executable  $@
